# Generated by Django 4.2.13 on 2024-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Design', 'Design'), ('Other', 'Other')], max_length=100),
        ),
    ]
